openapi: 3.0.3
info:
  title: Blog API
  description: API for managing blog posts with topics and hashtags
  version: 1.0.0

servers:
  - url: /api
    description: API base path

paths:
  /blog:
    get:
      summary: List blog posts
      description: Get a paginated list of blog posts with optional filtering
      operationId: listBlogs
      tags:
        - Blog
      parameters:
        - name: status
          in: query
          description: Filter by post status
          schema:
            type: string
            enum: [DRAFT, PUBLISHED]
        - name: topicId
          in: query
          description: Filter by topic ID
          schema:
            type: string
            format: uuid
        - name: hashtagId
          in: query
          description: Filter by hashtag ID
          schema:
            type: string
            format: uuid
        - name: search
          in: query
          description: Search in title and content
          schema:
            type: string
        - name: page
          in: query
          description: Page number (0-indexed)
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: limit
          in: query
          description: Items per page
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
      responses:
        "200":
          description: List of blog posts
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                  - pagination
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/BlogWithRelations"
                  pagination:
                    $ref: "#/components/schemas/Pagination"

    post:
      summary: Create blog post
      description: Create a new blog post (super admin only)
      operationId: createBlog
      tags:
        - Blog
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBlogRequest"
      responses:
        "201":
          description: Blog post created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BlogWithRelations"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
        "409":
          description: Slug already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /blog/{id}:
    get:
      summary: Get blog post
      description: Get a single blog post by ID
      operationId: getBlog
      tags:
        - Blog
      parameters:
        - name: id
          in: path
          required: true
          description: Blog post ID
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Blog post found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BlogWithRelations"
        "404":
          description: Blog post not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      summary: Update blog post
      description: Update an existing blog post (super admin only)
      operationId: updateBlog
      tags:
        - Blog
      security:
        - sessionAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Blog post ID
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBlogRequest"
      responses:
        "200":
          description: Blog post updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BlogWithRelations"
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "404":
          description: Blog post not found
        "409":
          description: Slug already exists

    delete:
      summary: Delete blog post
      description: Delete a blog post and all its associations (super admin only)
      operationId: deleteBlog
      tags:
        - Blog
      security:
        - sessionAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Blog post ID
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Blog post deleted
        "401":
          description: Unauthorized
        "404":
          description: Blog post not found

components:
  schemas:
    Blog:
      type: object
      required:
        - id
        - title
        - slug
        - status
        - content
        - authorId
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          minLength: 1
          maxLength: 200
        slug:
          type: string
          pattern: "^[a-z0-9-]+$"
        status:
          type: string
          enum: [DRAFT, PUBLISHED]
        publishDate:
          type: string
          format: date-time
          nullable: true
        content:
          type: string
          minLength: 1
        excerpt:
          type: string
          nullable: true
        readTime:
          type: integer
          nullable: true
        coverImage:
          type: string
          format: uri
          nullable: true
        authorId:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    BlogWithRelations:
      allOf:
        - $ref: "#/components/schemas/Blog"
        - type: object
          required:
            - topics
            - hashtags
          properties:
            topics:
              type: array
              items:
                $ref: "#/components/schemas/Topic"
            hashtags:
              type: array
              items:
                $ref: "#/components/schemas/Hashtag"

    Topic:
      type: object
      required:
        - id
        - name
        - slug
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        description:
          type: string
          nullable: true

    Hashtag:
      type: object
      required:
        - id
        - name
        - slug
        - createdAt
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        description:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time

    CreateBlogRequest:
      type: object
      required:
        - title
        - slug
        - content
        - status
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        slug:
          type: string
          pattern: "^[a-z0-9-]+$"
        status:
          type: string
          enum: [DRAFT, PUBLISHED]
        publishDate:
          type: string
          format: date-time
        content:
          type: string
          minLength: 1
        excerpt:
          type: string
        coverImage:
          type: string
          format: uri
        topicIds:
          type: array
          items:
            type: string
            format: uuid
        hashtagIds:
          type: array
          items:
            type: string
            format: uuid

    UpdateBlogRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        slug:
          type: string
          pattern: "^[a-z0-9-]+$"
        status:
          type: string
          enum: [DRAFT, PUBLISHED]
        publishDate:
          type: string
          format: date-time
        content:
          type: string
          minLength: 1
        excerpt:
          type: string
        coverImage:
          type: string
          format: uri
        topicIds:
          type: array
          items:
            type: string
            format: uuid
        hashtagIds:
          type: array
          items:
            type: string
            format: uuid

    Pagination:
      type: object
      required:
        - page
        - limit
        - total
        - totalPages
      properties:
        page:
          type: integer
          minimum: 0
        limit:
          type: integer
          minimum: 1
        total:
          type: integer
          minimum: 0
        totalPages:
          type: integer
          minimum: 0

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object

  securitySchemes:
    sessionAuth:
      type: apiKey
      in: cookie
      name: session
