import type { DesignSystem } from '@/types/design-system';

/**
 * Design Systems Gallery Data
 * Each design system includes complete token definitions for colors,
 * typography, spacing, and shadows in both light and dark modes.
 */
export const DESIGN_SYSTEMS: DesignSystem[] = [
  {
    id: 'shadcn',
    name: 'shadcn/ui',
    slug: 'shadcn',
    description:
      'Neutral, minimalist design system with a focus on accessibility and developer experience.',
    author: 'shadcn',
    website: 'https://ui.shadcn.com',
    isDefault: true,
    preview: {
      primaryColor: '#ffffff',
      backgroundColor: '#0a0a0a',
      accentColor: '#737373',
    },
    tokens: {
      light: {
        background: '#ffffff',
        foreground: '#0a0a0a',
        card: '#f5f5f5',
        cardForeground: '#0a0a0a',
        popover: '#ffffff',
        popoverForeground: '#0a0a0a',
        primary: '#0a0a0a',
        primaryForeground: '#ffffff',
        secondary: '#f5f5f5',
        secondaryForeground: '#0a0a0a',
        muted: '#f5f5f5',
        mutedForeground: '#737373',
        accent: '#f5f5f5',
        accentForeground: '#0a0a0a',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        border: '#e5e5e5',
        input: '#e5e5e5',
        ring: '#0a0a0a',
        glow1: '#1e3a8a',
        glow2: '#581c87',
      },
      dark: {
        background: '#0a0a0a',
        foreground: '#d4d4d4',
        card: '#171717',
        cardForeground: '#ffffff',
        popover: '#0a0a0a',
        popoverForeground: '#d4d4d4',
        primary: '#ffffff',
        primaryForeground: '#000000',
        secondary: '#171717',
        secondaryForeground: '#ffffff',
        muted: '#171717',
        mutedForeground: '#737373',
        accent: '#262626',
        accentForeground: '#ffffff',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        border: '#262626',
        input: '#262626',
        ring: '#ffffff',
        glow1: '#1e3a8a',
        glow2: '#581c87',
      },
    },
    typography: {
      fontSans: "'Inter', ui-sans-serif, system-ui, sans-serif",
      fontMono: "'JetBrains Mono', 'Fira Code', monospace",
      letterSpacing: '-0.01em',
    },
    spacing: {
      radius: '0.375rem',
      bentoRadius: '16px',
    },
  },
  {
    id: 'vercel',
    name: 'Vercel',
    slug: 'vercel',
    description:
      'High contrast black and white design with sharp edges and bold typography.',
    author: 'Vercel',
    website: 'https://vercel.com',
    isDefault: false,
    preview: {
      primaryColor: '#000000',
      backgroundColor: '#000000',
      accentColor: '#0070f3',
    },
    tokens: {
      light: {
        background: '#ffffff',
        foreground: '#000000',
        card: '#fafafa',
        cardForeground: '#000000',
        popover: '#ffffff',
        popoverForeground: '#000000',
        primary: '#000000',
        primaryForeground: '#ffffff',
        secondary: '#fafafa',
        secondaryForeground: '#000000',
        muted: '#f5f5f5',
        mutedForeground: '#666666',
        accent: '#0070f3',
        accentForeground: '#ffffff',
        destructive: '#ee0000',
        destructiveForeground: '#ffffff',
        border: '#eaeaea',
        input: '#eaeaea',
        ring: '#0070f3',
        glow1: '#0070f3',
        glow2: '#7928ca',
      },
      dark: {
        background: '#000000',
        foreground: '#ededed',
        card: '#111111',
        cardForeground: '#ededed',
        popover: '#000000',
        popoverForeground: '#ededed',
        primary: '#ffffff',
        primaryForeground: '#000000',
        secondary: '#111111',
        secondaryForeground: '#ededed',
        muted: '#111111',
        mutedForeground: '#888888',
        accent: '#0070f3',
        accentForeground: '#ffffff',
        destructive: '#ee0000',
        destructiveForeground: '#ffffff',
        border: '#333333',
        input: '#333333',
        ring: '#0070f3',
        glow1: '#0070f3',
        glow2: '#7928ca',
      },
    },
    typography: {
      fontSans: "'Geist', 'Inter', ui-sans-serif, system-ui, sans-serif",
      fontMono: "'Geist Mono', 'Fira Code', monospace",
      letterSpacing: '-0.02em',
    },
    spacing: {
      radius: '0.5rem',
      bentoRadius: '12px',
    },
  },
  {
    id: 'linear',
    name: 'Linear',
    slug: 'linear',
    description:
      'Purple gradient-focused design with elegant dark mode and smooth transitions.',
    author: 'Linear',
    website: 'https://linear.app',
    isDefault: false,
    preview: {
      primaryColor: '#5e6ad2',
      backgroundColor: '#0e0e10',
      accentColor: '#5e6ad2',
    },
    tokens: {
      light: {
        background: '#f9f9fb',
        foreground: '#1a1a1a',
        card: '#ffffff',
        cardForeground: '#1a1a1a',
        popover: '#ffffff',
        popoverForeground: '#1a1a1a',
        primary: '#5e6ad2',
        primaryForeground: '#ffffff',
        secondary: '#f0f0f3',
        secondaryForeground: '#1a1a1a',
        muted: '#e8e8ec',
        mutedForeground: '#6b6b76',
        accent: '#5e6ad2',
        accentForeground: '#ffffff',
        destructive: '#e5484d',
        destructiveForeground: '#ffffff',
        border: '#e4e4e8',
        input: '#e4e4e8',
        ring: '#5e6ad2',
        glow1: '#5e6ad2',
        glow2: '#a855f7',
      },
      dark: {
        background: '#0e0e10',
        foreground: '#e8e8ec',
        card: '#16161a',
        cardForeground: '#e8e8ec',
        popover: '#16161a',
        popoverForeground: '#e8e8ec',
        primary: '#5e6ad2',
        primaryForeground: '#ffffff',
        secondary: '#26262c',
        secondaryForeground: '#e8e8ec',
        muted: '#1c1c20',
        mutedForeground: '#6b6b76',
        accent: '#5e6ad2',
        accentForeground: '#ffffff',
        destructive: '#e5484d',
        destructiveForeground: '#ffffff',
        border: '#26262c',
        input: '#26262c',
        ring: '#5e6ad2',
        glow1: '#5e6ad2',
        glow2: '#a855f7',
      },
    },
    typography: {
      fontSans: "'Inter', ui-sans-serif, system-ui, sans-serif",
      fontMono: "'JetBrains Mono', monospace",
      letterSpacing: '-0.011em',
    },
    spacing: {
      radius: '0.375rem',
      bentoRadius: '8px',
    },
  },
  {
    id: 'stripe',
    name: 'Stripe',
    slug: 'stripe',
    description:
      'Clean blue accent design with professional feel and excellent readability.',
    author: 'Stripe',
    website: 'https://stripe.com',
    isDefault: false,
    preview: {
      primaryColor: '#635bff',
      backgroundColor: '#0a2540',
      accentColor: '#635bff',
    },
    tokens: {
      light: {
        background: '#ffffff',
        foreground: '#425466',
        card: '#f6f9fc',
        cardForeground: '#0a2540',
        popover: '#ffffff',
        popoverForeground: '#425466',
        primary: '#635bff',
        primaryForeground: '#ffffff',
        secondary: '#f6f9fc',
        secondaryForeground: '#0a2540',
        muted: '#f6f9fc',
        mutedForeground: '#8798a5',
        accent: '#635bff',
        accentForeground: '#ffffff',
        destructive: '#df1b41',
        destructiveForeground: '#ffffff',
        border: '#e6ebf1',
        input: '#e6ebf1',
        ring: '#635bff',
        glow1: '#635bff',
        glow2: '#00d4ff',
      },
      dark: {
        background: '#0a2540',
        foreground: '#adbdcc',
        card: '#0f3058',
        cardForeground: '#ffffff',
        popover: '#0f3058',
        popoverForeground: '#adbdcc',
        primary: '#635bff',
        primaryForeground: '#ffffff',
        secondary: '#0f3058',
        secondaryForeground: '#ffffff',
        muted: '#1a3d5c',
        mutedForeground: '#8798a5',
        accent: '#635bff',
        accentForeground: '#ffffff',
        destructive: '#df1b41',
        destructiveForeground: '#ffffff',
        border: '#1a3d5c',
        input: '#1a3d5c',
        ring: '#635bff',
        glow1: '#635bff',
        glow2: '#00d4ff',
      },
    },
    typography: {
      fontSans:
        "'Söhne', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      fontMono: "'Söhne Mono', 'Menlo', monospace",
      letterSpacing: '0em',
    },
    spacing: {
      radius: '0.5rem',
      bentoRadius: '12px',
    },
  },
  {
    id: 'tailwind',
    name: 'Tailwind',
    slug: 'tailwind',
    description:
      'Cyan/sky accent with utility-first philosophy and modern gradients.',
    author: 'Tailwind Labs',
    website: 'https://tailwindcss.com',
    isDefault: false,
    preview: {
      primaryColor: '#0ea5e9',
      backgroundColor: '#0f172a',
      accentColor: '#38bdf8',
    },
    tokens: {
      light: {
        background: '#ffffff',
        foreground: '#0f172a',
        card: '#f8fafc',
        cardForeground: '#0f172a',
        popover: '#ffffff',
        popoverForeground: '#0f172a',
        primary: '#0ea5e9',
        primaryForeground: '#ffffff',
        secondary: '#f1f5f9',
        secondaryForeground: '#0f172a',
        muted: '#f1f5f9',
        mutedForeground: '#64748b',
        accent: '#38bdf8',
        accentForeground: '#0f172a',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        border: '#e2e8f0',
        input: '#e2e8f0',
        ring: '#0ea5e9',
        glow1: '#0ea5e9',
        glow2: '#8b5cf6',
      },
      dark: {
        background: '#0f172a',
        foreground: '#e2e8f0',
        card: '#1e293b',
        cardForeground: '#e2e8f0',
        popover: '#1e293b',
        popoverForeground: '#e2e8f0',
        primary: '#38bdf8',
        primaryForeground: '#0f172a',
        secondary: '#1e293b',
        secondaryForeground: '#e2e8f0',
        muted: '#334155',
        mutedForeground: '#94a3b8',
        accent: '#38bdf8',
        accentForeground: '#0f172a',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        border: '#334155',
        input: '#334155',
        ring: '#38bdf8',
        glow1: '#0ea5e9',
        glow2: '#8b5cf6',
      },
    },
    typography: {
      fontSans: "'Inter', ui-sans-serif, system-ui, sans-serif",
      fontMono: "'Fira Code', 'JetBrains Mono', monospace",
      letterSpacing: '-0.025em',
    },
    spacing: {
      radius: '0.5rem',
      bentoRadius: '16px',
    },
  },
];

/**
 * Get a design system by its slug
 */
export function getDesignSystemBySlug(slug: string): DesignSystem | undefined {
  return DESIGN_SYSTEMS.find((ds) => ds.slug === slug);
}

/**
 * Get the default design system
 */
export function getDefaultDesignSystem(): DesignSystem {
  return DESIGN_SYSTEMS.find((ds) => ds.isDefault) || DESIGN_SYSTEMS[0];
}

/**
 * Token categories for display
 */
export const TOKEN_CATEGORIES = [
  {
    id: 'colors',
    name: 'Colors',
    description: 'Core color tokens for backgrounds, text, and accents',
  },
  {
    id: 'semantic',
    name: 'Semantic Colors',
    description: 'Purpose-based colors for UI states',
  },
  {
    id: 'typography',
    name: 'Typography',
    description: 'Font families, sizes, and letter spacing',
  },
  {
    id: 'spacing',
    name: 'Spacing & Radius',
    description: 'Border radius and component gaps',
  },
  {
    id: 'components',
    name: 'Components',
    description: 'UI component previews with applied tokens',
  },
] as const;
